Repository DGBTechnologies/storm_dft, pull requests merged in 2022-11, with the labels that each got.

#1 image path isssue resolved
  index.html
  storm-dft.html
Labels: enhancement

#2 responssiveness increse
  .vscode/settings.json
  index.css
  index.html
  src/components/case_studies/dft-case-studies.html
  src/components/dcumentations/dft-documentations.html
  src/components/getting_started/dft-getting-started.css
  src/components/getting_started/dft-getting-started.html
  src/components/support/dft-support.css
  src/components/support/dft-support.html
Labels: CSS updated

#4 overflow set
  src/commonUI/navbar.html
Labels: bug, CSS updated

#5 documentation video adjustment
  src/components/dcumentations/dft-documentations.html
Labels: CSS updated

#6 landing page changed
  index.css
  index.html
  script.js
Labels: enhancement

#7 index slider
  index.css
  index.html
Labels: enhancement

#8 tool features changed
  src/assets/images/discussion.jpg
  src/assets/images/graph.png
  src/assets/images/modular.png
  src/assets/images/simplify.png
  src/assets/images/simulation.png
  src/assets/images/sysml-dft.png
  src/assets/images/youtube.png
  src/components/dft_introduction/dft-introduction.html
  src/components/tool_features/dft-tool-features.html
Labels: enhancement

#9 sticky navbar in documentationand licence
  src/components/dcumentations/dft-documentations.html
  src/components/licences/dft-licenses.css
  src/components/licences/dft-licenses.html
Labels: CSS updated

#10 slider testimonial added
  index.css
  index.html
  src/assets/images/left-quotes-sign.png
  src/assets/images/man.png
  src/assets/images/man2.png
  src/assets/images/right-quotes-sign.png
  src/assets/images/woman.png
  src/components/licences/dft-licenses.html
Labels: enhancement

#11 minner changes
  index.css
  src/commonUI/navbar.html
  src/components/collaborator/collaborator.html
  src/components/collaborator/collaburator.css
Labels: enhancement

#13 colaborator page structure defined
  src/components/collaborator/collaborator.html
  src/components/collaborator/collaburator.css
  src/components/dcumentations/dft-documentations.html
  src/components/getting_started/dft-getting-started.html
Labels: enhancement, new feature

#12 Licences Popup added for Agreement Content
  src/components/licences/dft-licenses.html
Labels: enhancement, new feature

#14 Licence cards added
  src/components/licences/dft-licenses.html
Labels: enhancement

#15 collaborator edited
  src/assets/images/apple.png
  src/assets/images/discord.png
  src/assets/images/huawei.png
  src/assets/images/mcdonalds.png
  src/assets/images/nike.png
  src/components/collaborator/collaborator.html
  src/components/support/dft-support.css
  src/components/support/dft-support.html
Labels: enhancement

#16 colaburator client updated
  src/components/collaborator/collaborator.html
Labels: enhancement

#17 licence table added
  src/components/licences/dft-licenses.html
Labels: enhancement

#19 css style updated
  src/assets/images/aachen.png
  src/assets/images/bosch.png
  src/assets/images/twente.png
  src/components/case_studies/dft-case-studies.css
  src/components/case_studies/dft-case-studies.html
  src/components/collaborator/collaborator.html
  src/components/collaborator/collaburator.css
  src/components/dcumentations/dft-documentations.html
  src/components/dcumentations/dft-documetations.css
  src/components/dft_introduction/dft-introduction.css
  src/components/dft_introduction/dft-introduction.html
  src/components/getting_started/dft-getting-started.css
  src/components/getting_started/dft-getting-started.html
  src/components/licences/dft-licenses.css
  src/components/licences/dft-licenses.html
  src/components/support/dft-support.css
  src/components/support/dft-support.html
  src/components/team/dft-team.css
  src/components/team/dft-team.html
  src/components/tool_features/dft-tool-features.css
  src/components/tool_features/dft-tool-features.html
Labels: CSS updated

#21 css styles updated | spell error removed 2
  src/components/tool_features/dft-tool-features.html
Labels: enhancement

#22 licence changes
  index.css
  src/components/licences/dft-licenses.html
Labels: enhancement

#23 index testimonial border removed
  index.css
  index.html
  src/components/dft_introduction/dft-introduction.html
  src/components/licences/dft-licenses.html
  src/components/licenses/dft-licenses.html
Labels: enhancement

#24 licence page changed
  src/components/licenses/dft-licenses.html
Labels: enhancement, CSS updated
